<?php

return [
    'employment_status' => [
        'activo' => 'Activo',
        'desvinculado' => 'Desvinculado',
    ],

    'import_columns' => [
        'cedula' => 'Cédula (obligatorio)',
        'nombre' => 'Nombre completo',
        'fecha_nac' => 'Fecha nacimiento (YYYY-MM-DD)',
        'tipo_documento' => 'Tipo documento (C, TI, etc.)',
        'codigo_lugar_exp_cedula' => 'Código lugar expedición',
        'lugar_exp_cedula' => 'Lugar expedición',
        'fecha_expedicion' => 'Fecha expedición',
        'codigo_lugar_residencia' => 'Código ciudad residencia DANE',
        'lugar_residencia' => 'Ciudad residencia',
        'direccion' => 'Dirección',
        'telefono' => 'Teléfono',
        'tipo_sangre' => 'Tipo sangre',
        'sexo' => 'Sexo (M/F)',
        'salario' => 'Salario',
        'escolaridad' => 'Escolaridad',
        'estado_civil' => 'Estado civil',
        'numero_hijos' => 'Número hijos',
        'email' => 'Correo electrónico',
        'tipo_vinculacion' => 'Tipo vinculación',
        'tipo_cotizante' => 'Tipo cotizante',
        'fecha_ingreso' => 'Fecha ingreso (YYYY-MM-DD)',
        'fecha_vencimiento_contrato' => 'Fecha vencimiento contrato',
        'fecha_retiro' => 'Fecha retiro (vacío = activo)',
        'nombre_centro_trabajo' => 'Nombre centro trabajo',
        'ccosto' => 'Código centro costo',
        'nombre_ccosto' => 'Nombre centro costo',
        'cargo' => 'Código cargo',
        'nombre_cargo' => 'Nombre cargo',
        'escala' => 'Escala',
        'tipo_salario' => 'Tipo salario',
        'tipo_contrato' => 'Tipo contrato',
        'codigo_eps' => 'Código EPS',
        'nombre_eps' => 'Nombre EPS',
        'codigo_afp' => 'Código AFP',
        'nombre_afp' => 'Nombre AFP',
        'nombre_arp' => 'Nombre ARP',
        'nivel_riesgo_arp' => 'Nivel riesgo ARP',
        'nombre_caja_compensacion' => 'Caja compensación',
        'banco' => 'Banco / código banco',
        'tipo_de_cuenta' => 'Tipo cuenta (1/2)',
        'cuenta' => 'Número cuenta',
        'forma_pago' => 'Forma pago',
        'actividad_economica' => 'Código actividad económica',
        'nombre_actividad_economica' => 'Nombre actividad económica',
        'codigo_requisicion' => 'Código requisición (opcional)',
    ],

    'plantilla_masivos_template' => storage_path('templates/plantilla-masivos.xlsx'),

    'plantilla_masivos_columns' => [
        'TMPCEDULA.C15',
        'CLASEDOC.C1',
        'TMPNOMBRE.C40',
        'TMPAPELL_1.C60',
        'TMPAPELL_2.C60',
        'TMPNOMB_1.C60',
        'TMPNOMB_2.C60',
        'TMPDIRECCI.C40',
        'TMPTELEFON.C19',
        'TMPTELEF2.C19',
        'TMPEMAIL.C40',
        'TMPCIUDAD.C5',
        'TMPCIUNOM.C30',
        'FECNACIDO.C10',
        'FECHAING.C10',
        'FECHAVACA.C10',
        'TIPOVNC.N1',
        'CODCARGO.C10',
        'NOMCARGO.C30',
        'FORPAGO.C10',
        'CODBANCO.C10',
        'NOMBANCO.C30',
        'BANCUENTA.C20',
        'TIPOCUENTA.N1',
        'CODCENTROTB.C10',
        'NITCENTROTB.C15',
        'NOMCENTROTB.C30',
        'SALARIO.N12',
        'CODEPS.C10',
        'NOMEPS.C30',
        'FECINGEPS.C10',
        'CODAFP.C10',
        'NOMAFP.C30',
        'FECINGAFP.C10',
        'CODARP.C10',
        'NOMARP.C30',
        'TASAARP.C10',
        'CODCCF.C10',
        'NOMCCF.C30',
        'LIBRETA.C20',
        'SEXO.C1',
        'CODTPSALAR.C10',
        'NOMTPSALAR.C50',
        'CODTPCONTR.C10',
        'NOMTPCONTR.C50',
        'FECHAVCTO.C10',
        'JORNADA.N1',
        'TPRTFTE.N1',
        'TPGASTO.N1',
        'CODADCESAN.C10',
        'NOMADCESAN.C50',
        'CODSUCURS.C5',
        'NOMSUCURS.C50',
        'CODCCOSTO.C10',
        'NOMCCOSTO.C50',
        'CODDESTINO.C10',
        'NOMDESTINO.C50',
        'CODZONA.C5',
        'NOMZONA.C50',
        'CODACTARL.C10',
        'NOMACTARL.C50',
        'EXCLAUXTRA.N1',
    ],

    'catalog_types' => [
        'document_type',
        'city',
        'position',
        'cost_center',
        'eps',
        'afp',
        'arp',
        'bank',
        'payment_method',
        'contract_type',
        'salary_type',
        'economic_activity',
        'branch',
    ],
];
